name: wheaterin
description: "A minimal glassmorphism weather app with live location, dynamic animations, and OpenWeatherMap integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600

  assets:
    - assets/
